export const Activities = [
  "Take a 10-minute walk in nature.",
  "Write down three things you're grateful for.",
  "Read a chapter of a motivational book.",
  "Try a new recipe.",
  "Watch a feel-good movie.",
  "Meditate for 5 minutes.",
  "Create a vision board.",
  "Listen to an uplifting podcast.",
  "Start a journal.",
  "Organize a small part of your room.",
  "Do a quick workout routine.",
  "Call a friend or family member.",
  "Try a new hobby or craft.",
  "Plant a small indoor plant.",
  "Declutter your phone apps.",
  "Write a positive affirmation.",
  "Cook a healthy meal.",
  "Spend time with a pet.",
  "Try a new hairstyle.",
  "Listen to your favorite music.",
  "Plan a future trip or adventure.",
  "Do a puzzle or brain teaser.",
  "Learn a few phrases in a new language.",
  "Write a letter to your future self.",
  "Watch a TED talk.",
  "Take a bubble bath.",
  "Volunteer for a local charity.",
  "Visit a museum or gallery online.",
  "Start a small DIY project.",
  "Read positive quotes.",
  "Practice deep breathing exercises.",
  "Make a list of your strengths.",
  "Take a nap without feeling guilty.",
  "Try yoga or stretching.",
  "Write down your goals for the month.",
  "Paint or draw something.",
  "Bake a cake or cookies.",
  "Spend time in a park.",
  "Write a thank you note to someone.",
  "Do something creative.",
  "Organize your wardrobe.",
  "Make a playlist of happy songs.",
  "Plan a fun day out.",
  "Watch funny videos online.",
  "Do a digital detox for an hour.",
  "Try a new workout class online.",
  "Take photos of things that make you happy.",
  "Clean your workspace.",
  "Start a new book.",
  "Write a list of things you love about yourself.",
  "Do a random act of kindness.",
  "Visit a local market.",
  "Make a healthy smoothie.",
  "Spend time in the sun.",
  "Watch the sunrise or sunset.",
  "Do a creative writing exercise.",
  "Have a picnic indoors.",
  "Practice gratitude before bed.",
  "Create a list of your favorite memories.",
  "Try a new sport or activity.",
  "Join an online class or workshop.",
  "Do a small home improvement task.",
  "Spend time with supportive friends.",
  "Learn about a new topic.",
  "Play a board game.",
  "Make a vision board for your dreams.",
  "Write about your feelings.",
  "Make a bucket list.",
  "Spend time doing nothing.",
  "Attend a virtual event or meetup.",
  "Treat yourself to something special.",
  "Reflect on your personal growth.",
  "Do a creative photoshoot.",
  "Listen to a new genre of music.",
  "Make a DIY face mask.",
  "Create a self-care routine.",
  "Try a guided meditation.",
  "Write a positive review for a business you love.",
  "Plan your meals for the week.",
  "Do a digital declutter.",
  "Make a list of things you want to learn.",
  "Write a poem or short story.",
  "Take a virtual tour of a place you want to visit.",
  "Make a list of things you love about your life.",
  "Practice self-compassion.",
  "Try a new app that promotes wellness.",
  "Spend a day exploring your city.",
  "Learn a new skill online.",
  "Write down your dreams and aspirations.",
  "Watch a documentary.",
  "Make a list of positive affirmations.",
  "Treat yourself to a favorite snack.",
  "Spend time people-watching at a cafe.",
  "Do a quick cleaning task.",
  "Create a scrapbook.",
  "Spend time with children or elderly.",
  "Write down your thoughts and feelings.",
  "Make a list of places you want to visit.",
  "Do a simple DIY project.",
  "Spend time in nature.",
  "Create a self-care jar with activity ideas.",
  "Listen to a motivational speaker.",
  "Celebrate your achievements, big or small.",
  "Learn to cook a dish from a different culture.",
  "Spend an hour reading a self-improvement article.",
  "Take a dance break to your favorite song.",
  "Write a letter to your past self.",
  "Experiment with a new art medium.",
  "Create a personal mantra.",
  "Spend time stargazing.",
  "Practice mindfulness for 10 minutes.",
  "Write a list of things that make you happy.",
  "Watch a motivational video.",
  "Make a photo album of happy moments.",
  "Create a morning routine.",
  "Plan a weekend getaway.",
  "Watch an inspiring biography.",
  "Learn a new word and use it in a sentence.",
  "Spend time with a friend you haven’t seen in a while.",
  "Try a new form of exercise.",
  "Spend time volunteering online.",
  "Make a collage of your goals.",
  "Write a positive review for a book you enjoyed.",
  "Make a list of things to look forward to.",
  "Do a crossword puzzle.",
  "Organize your bookshelf.",
  "Listen to a new podcast series.",
  "Practice positive self-talk.",
  "Spend time gardening.",
  "Try a new coffee or tea flavor.",
  "Write about your ideal future.",
  "Watch a movie in a foreign language.",
  "Make a list of your role models.",
  "Do a home spa day.",
  "Create a budget for something you want to save for.",
  "Make a playlist of calming music.",
  "Do a random act of kindness for a stranger.",
  "Learn about a historical event.",
  "Spend time painting rocks.",
  "Write down things you’re proud of.",
  "Do a DIY beauty treatment.",
  "Learn a new card game.",
  "Spend a day without social media.",
  "Write a story about your dream life.",
  "Watch a nature documentary.",
  "Make a list of fun things to do in your city.",
  "Do a simple sewing project.",
  "Write a list of things you want to improve about yourself.",
  "Take a virtual museum tour.",
  "Practice yoga for 20 minutes.",
  "Plan a themed movie night.",
  "Spend time doing nothing and enjoy it.",
  "Write a list of your favorite quotes.",
  "Do a creative writing prompt.",
  "Plan a day trip to somewhere new.",
  "Spend time doing a puzzle.",
  "Make a list of your favorite songs.",
  "Create a new recipe from scratch.",
  "Spend time people-watching in a park.",
  "Do a digital detox for a day.",
  "Write a letter to someone you admire.",
  "Take a new route on your daily walk.",
  "Plan a DIY project for your home.",
  "Spend time drawing or doodling.",
  "Write down your biggest dreams.",
  "Watch a comedy show.",
  "Make a list of things that inspire you.",
  "Spend time birdwatching.",
  "Write a list of things you want to learn.",
  "Do a simple meditation exercise.",
  "Make a scrapbook of your favorite memories.",
  "Watch a feel-good TV series.",
  "Spend time crafting something new.",
  "Write a poem about your feelings.",
  "Plan a fun outing with friends.",
  "Make a list of your favorite books.",
  "Create a gratitude jar.",
  "Spend time practicing a new skill.",
  "Watch a documentary about a subject you’re interested in.",
  "Write a list of things you want to achieve this year.",
  "Do a random act of kindness for someone you know.",
  "Spend time exploring a new hobby.",
  "Write a letter to your future self.",
  "Plan a fun weekend activity.",
  "Watch a movie that makes you laugh.",
  "Spend time practicing a musical instrument.",
  "Write a list of your favorite memories.",
  "Do a simple DIY home decor project.",
  "Spend time with positive people.",
  "Write a thank you note to someone who helped you.",
  "Make a list of things you’re excited about.",
  "Spend time journaling your thoughts.",
  "Do a creative photoshoot with your phone.",
  "Watch a motivational speech.",
  "Make a list of things you love about yourself.",
  "Spend time learning a new dance.",
  "Write a short story about a happy memory.",
  "Do a random act of kindness for a family member.",
  "Spend time practicing gratitude.",
  "Make a list of things you want to try.",
  "Watch a movie that inspires you.",
  "Spend time doing something creative.",
  "Write a letter to someone you miss.",
  "Plan a fun activity for the weekend.",
  "Make a list of your favorite quotes.",
  "Spend time enjoying your favorite hobby.",
];
